name: Build & Test for Ubuntu + Windows + OSX
on: [push]
jobs:
  run:
    name: Run Tests
    strategy:
      matrix:
        architecture: [x64, x86]
        operating-system: [macos-latest, windows-latest, ubuntu-latest, ubuntu-16.04]
        java-version: [8, 11]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
          java-package: jdk
          architecture: ${{ matrix.architecture }}
      - name: Install LLVM
        run: |
          gradle build --refresh-dependencies
      - name: Run tests
        run: |
          gradle clean test